### ISSUE TITLE
Reviewing a lot of submissions takes a lot of time.

### ISSUE THREAD

**Issue by basmulder03** [s0er3n/GeoBingo.io#32]
When playing with a lot of people it takes a really long time to  check every submission of every person. 
This makes so it takes a very long time which makes it very tedious to score every picture.
Is there a possibility that when there are above a certain amount of submissions, that every person just evaluates a certain number of each category and not every single item on every category, so this can be reduced. 

To make this possible in a user experience sort of way, I think that the veto rights of the host need to be removed, or that the host will still need to accept (or decline) every submissions. This can possible be made into a setting in the game settings.

**Comment by s0er3n** [comment]
I like the idea but it's not feasible for me to implement bc of time constraints. I hope you can understand.
